In [32]:
import numpy as np

In [33]:
rand_nums = np.random.uniform(10, 54000, 80)

In [34]:
rand_nums

array([19050.08014695, 10919.08579258, 39954.79128494, 13428.64913894,
       51469.38921282, 18028.51574846,  6039.32950606, 28534.53404827,
       36122.2378992 , 39950.89618535, 21657.86333766, 44037.0062312 ,
        5542.58360282, 11957.76366841, 52140.24173338, 33101.23573859,
       53590.62619952, 12372.93830904, 22849.08535541, 41203.04939188,
       29448.03698779, 11576.29276558, 47510.9103878 ,  6486.25702283,
       37833.45338664,  6046.3955796 ,  7975.12447336, 53415.57425529,
       48647.9679734 ,  1727.7034265 , 24977.72888514, 24182.16264332,
       45768.27987478, 20294.57600502, 38926.6264288 , 44371.48806914,
       13737.40642852, 32875.78913093, 30930.88312441, 44748.83308761,
       15764.91055141, 38104.64930025, 16075.23628166, 35695.87455604,
       12326.68315551, 20151.11631445, 10208.55064217, 21294.06748519,
       37170.95487358, 26445.15102351, 19748.76397356, 24770.75006239,
       40670.22050745,  6385.7719811 , 28447.82871404, 53067.05020549,
      

In [35]:
type(rand_nums)

numpy.ndarray

In [36]:
rand_nums.dtype

dtype('float64')

In [37]:
nearest_int = np.rint(rand_nums)

In [38]:
nearest_int

array([19050., 10919., 39955., 13429., 51469., 18029.,  6039., 28535.,
       36122., 39951., 21658., 44037.,  5543., 11958., 52140., 33101.,
       53591., 12373., 22849., 41203., 29448., 11576., 47511.,  6486.,
       37833.,  6046.,  7975., 53416., 48648.,  1728., 24978., 24182.,
       45768., 20295., 38927., 44371., 13737., 32876., 30931., 44749.,
       15765., 38105., 16075., 35696., 12327., 20151., 10209., 21294.,
       37171., 26445., 19749., 24771., 40670.,  6386., 28448., 53067.,
       26262.,  7268., 46181., 18290., 38354.,  9759., 11033.,  2135.,
       38081., 42665., 34257., 34351., 43826., 49852., 23576.,  1712.,
        4641., 17155., 53983., 47598., 19936., 45023., 48535., 23956.])

### Choosing best data type
#### it is int64 which is the same as int

In [39]:
converted_nums = nearest_int.astype(np.int64)

In [40]:
converted_nums

array([19050, 10919, 39955, 13429, 51469, 18029,  6039, 28535, 36122,
       39951, 21658, 44037,  5543, 11958, 52140, 33101, 53591, 12373,
       22849, 41203, 29448, 11576, 47511,  6486, 37833,  6046,  7975,
       53416, 48648,  1728, 24978, 24182, 45768, 20295, 38927, 44371,
       13737, 32876, 30931, 44749, 15765, 38105, 16075, 35696, 12327,
       20151, 10209, 21294, 37171, 26445, 19749, 24771, 40670,  6386,
       28448, 53067, 26262,  7268, 46181, 18290, 38354,  9759, 11033,
        2135, 38081, 42665, 34257, 34351, 43826, 49852, 23576,  1712,
        4641, 17155, 53983, 47598, 19936, 45023, 48535, 23956])

In [41]:
converted_nums.dtype

dtype('int64')

In [42]:
reshaped_conv_nums = converted_nums.reshape(8, 10)

In [43]:
reshaped_conv_nums

array([[19050, 10919, 39955, 13429, 51469, 18029,  6039, 28535, 36122,
        39951],
       [21658, 44037,  5543, 11958, 52140, 33101, 53591, 12373, 22849,
        41203],
       [29448, 11576, 47511,  6486, 37833,  6046,  7975, 53416, 48648,
         1728],
       [24978, 24182, 45768, 20295, 38927, 44371, 13737, 32876, 30931,
        44749],
       [15765, 38105, 16075, 35696, 12327, 20151, 10209, 21294, 37171,
        26445],
       [19749, 24771, 40670,  6386, 28448, 53067, 26262,  7268, 46181,
        18290],
       [38354,  9759, 11033,  2135, 38081, 42665, 34257, 34351, 43826,
        49852],
       [23576,  1712,  4641, 17155, 53983, 47598, 19936, 45023, 48535,
        23956]])

In [44]:
np.min(reshaped_conv_nums)

1712

In [45]:
np.max(reshaped_conv_nums)

53983

In [46]:
converted_int8 = reshaped_conv_nums.astype(np.int8)

In [47]:
converted_int8

array([[ 106,  -89,   19,  117,   13,  109, -105,  119,   26,   15],
       [-102,    5,  -89,  -74,  -84,   77,   87,   85,   65,  -13],
       [   8,   56, -105,   86,  -55,  -98,   39,  -88,    8,  -64],
       [-110,  118,  -56,   71,   15,   83,  -87,  108,  -45,  -51],
       [-107,  -39,  -53,  112,   39,  -73,  -31,   46,   51,   77],
       [  37,  -61,  -34,  -14,   32,   75, -106,  100,  101,  114],
       [ -46,   31,   25,   87,  -63,  -87,  -47,   47,   50,  -68],
       [  24,  -80,   33,    3,  -33,  -18,  -32,  -33, -105, -108]],
      dtype=int8)

In [48]:
C_two = tuple(converted_int8[:, 1])

In [49]:
C_two

(-89, 5, 56, 118, -39, -61, 31, -80)

In [50]:
R_three = list(converted_int8[2, 2:])

In [51]:
R_three

[-105, 86, -55, -98, 39, -88, 8, -64]

In [59]:
_dict = dict(zip(C_two, R_three))

In [60]:
_dict

{-89: -105, 5: 86, 56: -55, 118: -98, -39: 39, -61: -88, 31: 8, -80: -64}