In [1]:
import numpy as np

### Generate an array of 80 random numbers between 10 and 54,000

In [2]:
rand_nums = np.random.uniform(10, 54000, 80)

In [3]:
rand_nums

array([  630.51005006,  3646.30876843, 12979.41690935, 28873.11970045,
       47454.34415596, 30254.9416315 ,  7409.18375697, 34389.5704806 ,
       20362.23840516,  4764.75689231,  8206.65670055, 23853.08707532,
       21926.27069459, 43070.21139602, 48527.33250611,  8060.14178857,
       14977.85957418, 10677.56107675,  7232.33511965,  6256.96123948,
       52295.65017427, 34514.57515895, 30070.54437482, 16113.04261733,
       30025.15740842, 46870.71211332, 21428.675554  , 45291.34851143,
       53893.24529434, 30813.45006939,  3430.22179943, 31010.65277053,
        5626.01695924, 15109.37840609, 38789.53039708, 24740.35645084,
       38704.06376058, 12728.85290987, 38292.86741632, 52009.09825029,
       41999.61796869, 28328.35742422,  7838.0619894 , 36581.65963251,
       18180.11158381, 24746.07334599, 25721.76220276, 39049.05091389,
       11951.35147006, 38345.70225936, 27698.40330488,  7565.78437694,
       29575.44206452, 25785.30505828, 28658.89463413, 31115.90334771,
      

### Check the data type of the generated array

In [4]:
type(rand_nums)

numpy.ndarray

In [5]:
rand_nums.dtype

dtype('float64')

### Round each element in the array to the nearest integer

In [6]:
nearest_int = np.rint(rand_nums)

In [7]:
nearest_int

array([  631.,  3646., 12979., 28873., 47454., 30255.,  7409., 34390.,
       20362.,  4765.,  8207., 23853., 21926., 43070., 48527.,  8060.,
       14978., 10678.,  7232.,  6257., 52296., 34515., 30071., 16113.,
       30025., 46871., 21429., 45291., 53893., 30813.,  3430., 31011.,
        5626., 15109., 38790., 24740., 38704., 12729., 38293., 52009.,
       42000., 28328.,  7838., 36582., 18180., 24746., 25722., 39049.,
       11951., 38346., 27698.,  7566., 29575., 25785., 28659., 31116.,
       28827., 32336.,  9892., 35100.,  2280., 14097.,  6209., 16989.,
       49780., 28670., 22824., 48188., 40893., 53688., 26784., 25027.,
       38510., 52428., 15048., 23936., 37233., 43540., 18763., 18153.])

### Limitations of Several Numerical Data Types and Their Memory Occupancy


<ol>
  <li><strong>int</strong>: Default integer type (int64), varies by platform (usually 32 or 64 bits).
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Platform-dependent, could be overkill for small ranges.</li>
    <li><strong>Memory</strong>: 4 or 8 bytes</li>
  </ul></li>

   <br>

   <li><strong>int8</strong>: 8-bit signed integer.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Limited range (-2<sup>7</sup> to 2<sup>7</sup> - 1), potential for overflow.
    <li><strong>Memory</strong>: 1 byte</li>
  </ul></li>

   <br>

  <li><strong>uint8</strong>: 8-bit unsigned integer.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Limited range (0 to 2<sup>8</sup>), potential for overflow.
    <li><strong>Memory</strong>: 1 byte</li>
  </ul></li>

   <br>

  <li><strong>int16</strong>: 16-bit signed integer.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Limited range (-2<sup>15</sup> to 2<sup>15</sup> - 1), potential for overflow.
    <li><strong>Memory</strong>: 2 byte</li>
  </ul></li>

   <br>

  <li><strong>uint16</strong>: 16-bit unsigned integer.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Limited range (0 to 2<sup>16</sup> - 1), potential for overflow.
    <li><strong>Memory</strong>: 2 byte</li>
  </ul></li>

   <br>

  <li><strong>int32</strong>: 32-bit signed integer.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Could be overkill for small ranges.
    <li><strong>Memory</strong>: 4 byte</li>
  </ul></li>

   <br>

  <li><strong>int64</strong>: 64-bit signed integer.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Even more overkill for small ranges, higher memory consumption.
    <li><strong>Memory</strong>: 8 byte</li>
  </ul></li>

   <br>

  <li><strong>float</strong>: Platform-dependent floating-point (usually equivalent to float64).
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Possible overkill for integer data, more memory consumption.
    <li><strong>Memory</strong>: 8 bytes (usually)</li>
  </ul></li>

   <br>

  <li><strong>float32</strong>: 32-bit floating-point.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Limited precision, not suitable for integer storage.
    <li><strong>Memory</strong>: 4 byte</li>
  </ul></li>

   <br>

  <li><strong>float64</strong>: 64-bit floating-point.
  <ul style="margin-top:0.5em;">
    <li><strong>Limitation</strong>: Even more limited precision, highest memory consumption among these types.
    <li><strong>Memory</strong>: 8 bytes</li>
  </ul></li>

</ol>

### The best choice would be `uint16`.

- The unsigned 16-bit integer type allows for numbers between 0 and 65,535, which comfortably fits the range of 10 to 54,000 while consuming only 16 bits (or 2 bytes) of memory per element. It's the most memory-efficient choice without losing any data.


In [8]:
converted_nums = nearest_int.astype(np.uint16)

In [9]:
converted_nums

array([  631,  3646, 12979, 28873, 47454, 30255,  7409, 34390, 20362,
        4765,  8207, 23853, 21926, 43070, 48527,  8060, 14978, 10678,
        7232,  6257, 52296, 34515, 30071, 16113, 30025, 46871, 21429,
       45291, 53893, 30813,  3430, 31011,  5626, 15109, 38790, 24740,
       38704, 12729, 38293, 52009, 42000, 28328,  7838, 36582, 18180,
       24746, 25722, 39049, 11951, 38346, 27698,  7566, 29575, 25785,
       28659, 31116, 28827, 32336,  9892, 35100,  2280, 14097,  6209,
       16989, 49780, 28670, 22824, 48188, 40893, 53688, 26784, 25027,
       38510, 52428, 15048, 23936, 37233, 43540, 18763, 18153],
      dtype=uint16)

In [10]:
converted_nums.dtype

dtype('uint16')

### Reshape the 80-element array into an 8x10 matrix

In [11]:
reshaped_conv_nums = converted_nums.reshape(8, 10)

In [25]:
reshaped_conv_nums

array([[  631,  3646, 12979, 28873, 47454, 30255,  7409, 34390, 20362,
         4765],
       [ 8207, 23853, 21926, 43070, 48527,  8060, 14978, 10678,  7232,
         6257],
       [52296, 34515, 30071, 16113, 30025, 46871, 21429, 45291, 53893,
        30813],
       [ 3430, 31011,  5626, 15109, 38790, 24740, 38704, 12729, 38293,
        52009],
       [42000, 28328,  7838, 36582, 18180, 24746, 25722, 39049, 11951,
        38346],
       [27698,  7566, 29575, 25785, 28659, 31116, 28827, 32336,  9892,
        35100],
       [ 2280, 14097,  6209, 16989, 49780, 28670, 22824, 48188, 40893,
        53688],
       [26784, 25027, 38510, 52428, 15048, 23936, 37233, 43540, 18763,
        18153]], dtype=uint16)

### Find the minimum and maximum values in the reshaped array

In [27]:
np.min(reshaped_conv_nums)

631

In [28]:
np.max(reshaped_conv_nums)

53893

### Convert the reshaped array to 8-bit integers

- The conversion to 8-bit integers caused data truncation due to the limited range of `int8` (-128 to 127).

In [37]:
converted_int8 = reshaped_conv_nums.astype(np.int8)

In [39]:
converted_int8

array([[ 119,   62,  -77,  -55,   94,   47,  -15,   86, -118,  -99],
       [  15,   45,  -90,   62, -113,  124, -126,  -74,   64,  113],
       [  72,  -45,  119,  -15,   73,   23,  -75,  -21, -123,   93],
       [ 102,   35,   -6,    5, -122,  -92,   48,  -71, -107,   41],
       [  16,  -88,  -98,  -26,    4,  -86,  122, -119,  -81,  -54],
       [  50, -114, -121,  -71,  -13, -116, -101,   80,  -92,   28],
       [ -24,   17,   65,   93,  116,   -2,   40,   60,  -67,  -72],
       [ -96,  -61,  110,  -52,  -56, -128,  113,   20,   75,  -23]],
      dtype=int8)

### Extract the second column from the 8x10 matrix into a tuple

In [48]:
C_two = tuple(converted_int8[:, 1])

In [49]:
C_two

(-89, 5, 56, 118, -39, -61, 31, -80)

### Extract the third column from the 8x10 matrix into a tuple

In [50]:
R_three = list(converted_int8[2, 2:])

In [51]:
R_three

[-105, 86, -55, -98, 39, -88, 8, -64]

### Create a dictionary with C_two as keys and R_three as values

In [59]:
_dict = dict(zip(C_two, R_three))

In [60]:
_dict

{-89: -105, 5: 86, 56: -55, 118: -98, -39: 39, -61: -88, 31: 8, -80: -64}